database:
  dsn: "postgresql://bekheit:i2_LaXK9tP8HVPO7RJ6BHA@free-tier13.aws-eu-central-1.cockroachlabs.cloud:26257/defaultdb?sslmode=verify-full&options=--cluster%3Dsteep-alpaca-2628"

server:
  port: 8090

kafka:
  broker: "broker:29092"
  topic: "transaction"