apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  selector:
    app: kafka
  ports:
  - protocol: TCP
    name: p1
    port: 9092
    targetPort: 9092
  - protocol: TCP
    name: p2
    port: 29092
    targetPort: 29092
