apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction
  template:
    metadata:
      labels:
        app: transaction
    spec:
      containers:
      - name: transaction
        resources: {}
        image: bekheit/kub-transaction-app:latest
        env:
          - name: DSN
            value: "postgresql://bekheit:FZXiqs_RfqeqAFNpYd5v3A@free-tier13.aws-eu-central-1.cockroachlabs.cloud:26257/defaultdb?sslmode=verify-full&options=--cluster%3Dperky-opossum-4314"
          - name: PORT
            value: "8090"
          - name: POOL
            value: "8"
          - name: BROKER
            value: "kafka-service:29092"
          - name: TOPIC
            value: "transaction"