apiVersion: v1
kind: Service
metadata:
  name: transaction-consumer-service
spec:
  selector:
    app: transaction-consumer
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
